### ISSUE TITLE
⚙️ Install ESLint plugins

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-rules-default#14]
## Overview

* Install ESLint plugins

## Tasks

- [x] `eslint-plugin-jest`
- [x] `eslint-plugin-jsdoc`
- [x] `eslint-plugin-openreachtech`
