### ISSUE TITLE
🧹 Tidy up test

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-rules-default#192]
## Overview

* Tidy up test

## Tasks

- [x] Remove `sample.js`
- [x] `describe('eslintConfig')` to `'main exports'`
- [x] `describe('disable-core-stylistic')` to `'disable-core-stylistic rules'`
