### ISSUE TITLE
✅ Change package type to `commonjs`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-rules-default#206]
## Overview

* Change package type to `commonjs`

## Tasks

- [x] ⚙️ Change `type` field of `package.json` to `commonjs`
- [x] 💪 Change rule files as CommonJS
- [x] 💪 Change `jest.config.js` as CommonJS
- [x] 💪 Change test as CommonJS
- [x] 💪 Change `index.js` as CommonJS
- [x] 💪 Change `eslint.config.js` as CommonJS
