### ISSUE TITLE
🔧 Implement `index.mjs`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-rules-default#209]
## Overview

* Implement `index.mjs`

## Tasks

- [x] Add test for `index.mjs`
- [x] Add `index.mjs`
- [x] Fix test field of `package.json` to handle dynamic import
- [x] Add `index.mjs` to `ignore` field in `estlint.config.js`
- [x] Add `module` field into `jsconfig.json`
