### ISSUE TITLE
🚀 Publish `1.0.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-rules-default#215]
## Overview

* Publish version as `1.0.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #216
- [x] Publish.
- [x] #220
- [x] Push version tag `1.0.0` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `d0b5eaf`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/eslint-rules-default@1.0.0
  npm notice === Tarball Contents === 
  npm notice 1.1kB  LICENSE                        
  npm notice 4.8kB  README.ja.md                   
  npm notice 4.2kB  README.md                      
  npm notice 496B   index.js                       
  npm notice 554B   index.mjs                      
  npm notice 994B   package.json                   
  npm notice 16.8kB rules/core.js                  
  npm notice 2.3kB  rules/disable-core-stylistic.js
  npm notice 4.2kB  rules/plugins/jest.js          
  npm notice 15.1kB rules/plugins/jsdoc.js         
  npm notice 10.7kB rules/plugins/stylistic/js.js  
  npm notice 357B   rules/plugins/stylistic/plus.js
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/eslint-rules-default         
  npm notice version:       1.0.0                                       
  npm notice filename:      openreachtech-eslint-rules-default-1.0.0.tgz
  npm notice package size:  12.8 kB                                     
  npm notice unpacked size: 61.6 kB                                     
  npm notice shasum:        0dfec0000fab8a524381e07eb7bd1b57567f25a9    
  npm notice integrity:     sha512-bvRlqrgsVTDjI[...]gvwpapog4QNGQ==    
  npm notice total files:   12                                          
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @openreachtech/eslint-rules-default@1.0.0
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [ ] `npm publish`
