### ISSUE TITLE
🚀 Publish `1.0.1`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-rules-default#229]
## Overview

* Publish version as `1.0.1`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #230
- [x] Publish.
- [x] #232
- [x] Push version tag `1.0.1` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `3526fab`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/eslint-rules-default@1.0.1
  npm notice === Tarball Contents === 
  npm notice 1.1kB  LICENSE                        
  npm notice 4.7kB  README.ja.md                   
  npm notice 4.1kB  README.md                      
  npm notice 344B   index.js                       
  npm notice 431B   index.mjs                      
  npm notice 994B   package.json                   
  npm notice 16.8kB rules/core.js                  
  npm notice 2.3kB  rules/disable-core-stylistic.js
  npm notice 10.7kB rules/plugins/stylistic/js.js  
  npm notice 357B   rules/plugins/stylistic/plus.js
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/eslint-rules-default         
  npm notice version:       1.0.1                                       
  npm notice filename:      openreachtech-eslint-rules-default-1.0.1.tgz
  npm notice package size:  9.2 kB                                      
  npm notice unpacked size: 41.7 kB                                     
  npm notice shasum:        be00d7e9f8da81c2977fcb4fb1d5b1e17fd3d6e4    
  npm notice integrity:     sha512-8VUyhFipfG8P+[...]MJirAfGXrB8RQ==    
  npm notice total files:   10                                          
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @openreachtech/eslint-rules-default@1.0.1
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [x] `npm publish`
