### ISSUE TITLE
🚀 Publish `1.1.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-rules-default#256]
## Overview

* Publish version as `1.1.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #257
- [x] Publish.
- [x] #290
- [x] Push version tag `1.1.0` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `c7827e0`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/eslint-rules-default@1.1.0
  npm notice === Tarball Contents === 
  npm notice 1.1kB  LICENSE                                       
  npm notice 4.8kB  README.ja.md                                  
  npm notice 4.2kB  README.md                                     
  npm notice 17.5kB configurations/core.js                        
  npm notice 2.3kB  configurations/disable-core-stylistic.js      
  npm notice 330B   configurations/stylistic/all.js               
  npm notice 9.9kB  configurations/stylistic/default-rules/js.js  
  npm notice 214B   configurations/stylistic/default-rules/plus.js
  npm notice 11.3kB configurations/stylistic/js.js                
  npm notice 377B   configurations/stylistic/plus.js              
  npm notice 440B   index.js                                      
  npm notice 531B   index.mjs                                     
  npm notice 1.0kB  package.json                                  
  npm notice 423B   types/index.d.ts                              
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/eslint-rules-default         
  npm notice version:       1.1.0                                       
  npm notice filename:      openreachtech-eslint-rules-default-1.1.0.tgz
  npm notice package size:  11.0 kB                                     
  npm notice unpacked size: 54.5 kB                                     
  npm notice shasum:        7cdce05df07c132ea74d77d3363d166d00881399    
  npm notice integrity:     sha512-LjNjByYgSvAgX[...]3pyu1Unlzx5GA==    
  npm notice total files:   14                                          
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @openreachtech/eslint-rules-default@1.1.0
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [x] `npm publish`

**Comment by arbredoux** [comment]
```
$ npm publish --dry-run
npm notice
npm notice 📦  @openreachtech/eslint-rules-default@1.1.0
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 330B   configurations/stylistic/all.js
npm notice 17.5kB configurations/core.js
npm notice 2.3kB  configurations/disable-core-stylistic.js
npm notice 440B   index.js
npm notice 9.9kB  configurations/stylistic/default-rules/js.js
npm notice 11.3kB configurations/stylistic/js.js
npm notice 214B   configurations/stylistic/default-rules/plus.js
npm notice 377B   configurations/stylistic/plus.js
npm notice 1.0kB  package.json
npm notice 4.8kB  README.ja.md
npm notice 4.2kB  README.md
npm notice 531B   index.mjs
npm notice 423B   types/index.d.ts
npm notice === Tarball Details ===
npm notice name:          @openreachtech/eslint-rules-default
npm notice version:       1.1.0
npm notice package size:  11.0 kB
npm notice unpacked size: 54.5 kB
npm notice shasum:        8d1c0f95517650d0976ad3388b08d352234b4711
npm notice integrity:     sha512-mxqYqJ6raeP/f[...]X6VYduRsIAY2w==
npm notice total files:   14
npm notice
+ @openreachtech/eslint-rules-default@1.1.0
```

**Comment by arbredoux** [comment]
node の version を v20 に上げて再実行しました！
```
$ node -v
v20.12.1

$ npm -v
10.5.2
```
$ npm publish --dry-run
npm notice
npm notice 📦  @openreachtech/eslint-rules-default@1.1.0
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 4.8kB  README.ja.md
npm notice 4.2kB  README.md
npm notice 17.5kB configurations/core.js
npm notice 2.3kB  configurations/disable-core-stylistic.js
npm notice 330B   configurations/stylistic/all.js
npm notice 9.9kB  configurations/stylistic/default-rules/js.js
npm notice 214B   configurations/stylistic/default-rules/plus.js
npm notice 11.3kB configurations/stylistic/js.js
npm notice 377B   configurations/stylistic/plus.js
npm notice 440B   index.js
npm notice 531B   index.mjs
npm notice 1.0kB  package.json
npm notice 423B   types/index.d.ts
npm notice === Tarball Details ===
npm notice name:          @openreachtech/eslint-rules-default
npm notice version:       1.1.0
npm notice filename:      openreachtech-eslint-rules-default-1.1.0.tgz
npm notice package size:  11.0 kB
npm notice unpacked size: 54.5 kB
npm notice shasum:        7cdce05df07c132ea74d77d3363d166d00881399
npm notice integrity:     sha512-LjNjByYgSvAgX[...]3pyu1Unlzx5GA==
npm notice total files:   14
npm notice
npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
+ @openreachtech/eslint-rules-default@1.1.0
```

```

**Comment by StewEucen** [comment]
* Publish
https://github.com/openreachtech/eslint-rules-default/pkgs/npm/eslint-rules-default/224032421
