### ISSUE TITLE
⚙ Change `type` to ES Module

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-rules-default#35]
## Overview

* Change `type` to ES Module

## Tasks

- [x] ⚙️ Change `type` to `module` in `package.json`
- [x] 🧹 Adjust ESLint as ESM
- [x] 🧹 Adjust Jest as ESM
